### ISSUE TITLE
is it not working anymore ?

### ISSUE THREAD

**Issue by walaayakoot** [conradev/webn.es#11]
i tried the website on my pc and on my phone but its not working , am i missing anything ?

**Comment by conradev** [comment]
It does appear to be broken – at least, adding files to the emulator

**Comment by htv04** [comment]
I think this is because it uses the deprecated WebSQL for storage. The Dropbox API might be outdated too.

**Comment by conradev** [comment]
Yep! Let me file issues for what I'd love to see done

**Comment by conradev** [comment]
Closed in favor of #3 and #13
