### ISSUE TITLE
Web Audio API NES sounds gimped in Mobile Safari, iOS WKWebView, and Android Browsers

### ISSUE THREAD

**Issue by JoeMeeks** [conradev/webn.es#5]
Brilliant move, fellas, using Web Audio API for sound emulation. I am unlocking the audio context on touchend (due to breaking changes in iOS 9.2) but no dice playing back sound samples on ui.writeAudio in Mobile Safari, iOs WKWebViews, and Android Browsers. Working fine in my Chrome and Firefox desktop browsers, though.

Have you encountered a workaround? Silent NES is only half the fun :/

[Example here](http://joemeeks.net/tt17/)

**Comment by conradev** [comment]
Hi @JoeMeeks, sorry I didn't see this! The audio in webNES has always been a bit "gimped" ever since I got it working three years ago, and I never bothered to work on it since...

Are you saying it doesn't play at all anymore?
