### ISSUE TITLE
Not pixelated- solution provided

### ISSUE THREAD

**Issue by Heath123** [conradev/webn.es#6]
It looks blurred instead of pixelated. Easy fix: add this to the canvas in index.html.
`style="image-rendering: optimizeSpeed; image-rendering: -moz-crisp-edges; image-rendering: -webkit-optimize-contrast; image-rendering: -o-crisp-edges; image-rendering: pixelated; -ms-interpolation-mode: nearest-neighbor; "`
i.e. replace
`<canvas id="screen" width="256" height="240"></canvas>`
with
`<canvas id="screen" width="256" height="240" style="image-rendering: optimizeSpeed; image-rendering: -moz-crisp-edges; image-rendering: -webkit-optimize-contrast; image-rendering: -o-crisp-edges; image-rendering: pixelated; -ms-interpolation-mode: nearest-neighbor; "></canvas>`
Nothing needs to be changed other than index.html in my experience. An option could be provided to switch between nearest neighbor (what this enables) and linear interpolation (default).
Comparison: My method:
<img src="https://dl.dropboxusercontent.com/s/v1x6qezdek9lqz3/nn.png">
Default:
<img src="https://dl.dropboxusercontent.com/s/gwoepwpypkjz3bt/df.png">

**Comment by HTV04** [comment]
Will add this in my fork once I get webNES working again.

**Comment by HTV04** [comment]
Fixed in my fork: https://github.com/HTV04/htv04.github.io/tree/master/webnes-ce

**Comment by Heath123** [comment]
I suppose I didn't know what a PR was back in 2017...

**Comment by conradev** [comment]
@HTV04 want to upstream this? Closing for now
