### ISSUE TITLE
Sorry, but how to use it? Cannot find an entry to load .nes file

### ISSUE THREAD

**Issue by jslhcl** [conradev/webn.es#7]
Hi, 

I tried this project but I don't know how to start. Open index.html there is just description of this project, I cannot find an entry to load .nes files, nor how the js library is invoked. Can anybody help? 

BTW, the images in README.md cannot be found. 

![image](https://user-images.githubusercontent.com/1175624/45933947-6d6d2000-bfc9-11e8-836e-2e59f5992a24.png)

**Comment by HTV04** [comment]
Okay, so I made a fork of webNES [here](https://htv04.github.io), where I attempted to update the APIs. However, nothing still seems to work. I'm stuck here.
